version: '3.9'

# Docker Services
services:
    php:
        build:
          context: ${PROJECT_DIRECTORY}
          dockerfile: docker/php/Dockerfile
          args:
            - PHP_VERSION=$PHP_VERSION
        volumes:
            - ${PROJECT_DIRECTORY}:${SERVER_DIRECTORY}
        restart: unless-stopped
        tty: true
        networks:
          - frontend
        ports:
            - "8080:80"

# Docker Networks
networks:
  frontend:
    driver: bridge